management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  mail:
    host: ${EMAIL_HOST:smtp.exmail.qq.com}
    port: ${EMAIL_PORT:465}
    username: ${EMAIL_USERNAME:contact@boyouquan.com}
    password: ${EMAIL_PASSWORD:fake}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          timeout: 10000
          auth: true
          starttls:
            required: true
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

# self defined
boyouquan:
  email:
    enable: ${EMAIL_ENABLE:false}
  gravatar-url: https://cn.cravatar.com/avatar/%s?s=%d
  ip-info-query-url: https://whois.pconline.com.cn/ipJson.jsp?ip=%s&json=true
  domain-whois-info-query:
    url: https://api.jsonwhoisapi.com/v1/whois?identifier=%s
    api-key: ${DOMAIN_WHOIS_QUERY_API_KEY:fake_one}
  domains-refuse-to-join: qncd.com, xigeshudong.com, gregueria.icu
  cors:
    openWhiteList: ${CORS_OPEN_WHITE_LIST:true}
    whiteList: ${CORS_WHITE_LIST:http://localhost:3000}
  encryption:
    key: ${ENCRYPTION_KEY:boyouquan}
